name: test

on:
  push:
    branches: ["master"]
    tags: ["*"]
  pull_request:
    branches:
      - "*"
      - "!gh-pages"
    types: [review_requested, ready_for_review]

jobs:
  test:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.8, 3.9]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]
        rdkit-version: [2020.09, 2021.03]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Checkout the code
        uses: actions/checkout@v2

      - name: Cache conda
        uses: actions/cache@v2
        env:
          CACHE_NUMBER: 4
        with:
          path: ~/conda_pkgs_dir
          key: conda-${{ runner.os }}-${{ env.CACHE_NUMBER }}-${{ hashFiles('env.yml') }}-${{ matrix.python-version }}-${{ matrix.rdkit-version }}

      - name: Setup conda
        uses: conda-incubator/setup-miniconda@v2
        with:
          miniforge-variant: Mambaforge
          use-mamba: true
          use-only-tar-bz2: true
          auto-activate-base: true
          activate-environment: ""

      - name: Setup conda env
        run: |
          # Patch the conda env file to specify the Python and RDKit version
          mamba install --yes pyyaml

          python .github/patch_conda_env.py --env env.yml -d \
            python=${{ matrix.python-version }} \
            rdkit=${{ matrix.rdkit-version }} \
            > env-patched.yml

          # Create conda env
          mamba create -n datamol

      - name: Install Dependencies
        run: |
          conda activate datamol
          mamba env update -f env-patched.yml

      - name: Install library
        run: |
          conda activate datamol
          python -m pip install -e .  # `-e` required for correct `coverage` run.

      - name: Run tests
        run: |
          conda activate datamol
          pytest

      - name: Codecov Upload
        uses: codecov/codecov-action@v1
        with:
          files: ./coverage.xml
          flags: unittests
          name: codecov-umbrella
          fail_ci_if_error: true
          verbose: false
          env_vars: ${{ matrix.os }},${{ matrix.python-version }},${{ matrix.rdkit-version }}

      - name: Test building the doc
        run: |
          conda activate datamol

          # Build and serve the doc
          mkdocs build
